#version 450

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

const int HIT_MISS = 0;
const int HIT_SUCCESS = 1;
const float FOV = 1.0 * 1.57079632679; // 90 degrees, pi/2
const float PI = 3.14159265359;

// structs used
struct Camera {
    vec3 position;
    float padA;
    vec3 forward;
    float padB;
    vec3 right;
    float padC;
    vec3 up;
    float padD;

    float yaw;
    float pitch;
    float lastX;
    float lastY;
};

struct Material {
    vec3 color;
    float reflectivity;
    vec3 emissionColor;
    float emissionStrength;
};

struct Sphere {
    vec3 position;
    float radius;
    Material mat;
};

struct Triangle {
    vec3 v0;
    float padA;
    vec3 v1;
    float padB;
    vec3 v2;
    float padC;
    Material mat;
};

struct HomogenousVolume {
    vec3 absorptionCoefficient; // range: [0, 1]
    float padA;
    vec3 scatteringCoefficient; // range: [0, 1]
    float padB;
    vec3 extinctionCoefficient; // can be calculated via absorption + scattering, but don't feel like recalculating every time
    float padC; 
    
    // needs a bounding box
    vec3 minXYZ; // (x0, y0, z0)
    float padD;
    vec3 maxXYZ; // (x1, y1, z1)
    float padE;  // these two vertices is all you need for a bounding box
};

// internal struct used by compute shader, do not need to std430 align (nor std140 align)
struct Ray {
    vec3 origin;
    vec3 dir;
};

const int NULL_TYPE = -1;
const int SPHERE = 0;
const int TRIANGLE = 1;
const int VOLUME = 2;

struct Hit {
    int didHit;
    float t;
    float tNear;
    float tFar;
    vec3 position;
    vec3 normal;
    int type;
    Material mat;
    HomogenousVolume volume; // not always necessary
};

// layout bindings
layout(binding = 0) uniform UniformBufferObject {
    int width;
    int height;
    int sphereCount;
    int triangleCount;
    Camera camera;
    int NUM_SAMPLES;
    int MAX_DEPTH;
    int frameCount;
    int homogenousVolumesCount;
    float g; // Henyey-Greenstein asymmetry parameter. Range: [-1, 1]
    int emissiveSpheresCount;
    int emissiveTrianglesCount;
    int totalFrameCount;
};
layout (binding = 1, rgba32f) uniform image2D pixels;
layout (std430, binding = 2) buffer SphereBuffer {
    Sphere spheres[];
};
layout (std430, binding = 3) buffer TriangleBuffer {
    Triangle triangles[];
};
layout (std430, binding = 4) buffer HomogenousVolumesBuffer {
    HomogenousVolume homogenousVolumes[];
};
layout (std430, binding = 5) buffer EmissiveSpheresBuffer {
    Sphere emissiveSpheres[];
};
layout (std430, binding = 6) buffer EmissiveTrianglesBuffer {
    Triangle emissiveTriangles[];
};
layout (binding = 7) uniform sampler3D densityTexture;

uint state = uint(frameCount * 100);

// --- PCG Hash Algorithm ---
// Takes a 32-bit unsigned int state and returns a 32-bit pseudo-random unsigned int.
uint pcg() {
    uint state_old = state;
    // LCG step
    state = state_old * 747796405u + 2891336453u;
    // Xor shift step
    uint word = ((state_old >> ((state_old >> 28u) + 4u)) ^ state_old) * 277803737u;
    return (word >> 22u) ^ word;
}

// --- Float Conversion ---
// Returns a pseudo-random float in the range [0.0, 1.0)
float randf() {
    // Convert 32-bit int to a float between 0.0 and 1.0
    return float(pcg()) / 4294967296.0;
}

Ray makeRayFromCameraThroughPixel() {
    int x = int(gl_GlobalInvocationID.x);
    int y = int(gl_GlobalInvocationID.y);
    float px = x + randf(); // camera jittering for multiple samples per pixel
    float py = y + randf(); // why not lmao. idk how to make this more random

    float u = ((px) / float(width)) * 2 - 1;
    float v = ((py) / float(height)) * 2 - 1;

    float planeHalfHeight = tan(0.5f * FOV);
    float planeHalfWidth = planeHalfHeight * width / float(height);

    vec3 viewPlaneCenter = camera.position + camera.forward;
    vec3 pixelPoint = viewPlaneCenter + u * planeHalfWidth * camera.right;
    // NOTE: this means y=0 is top of screen!!!
    pixelPoint = pixelPoint - v * planeHalfHeight * camera.up;

    return Ray(
        camera.position,
        normalize(pixelPoint - camera.position)
    );
}

Material createEmptyMaterial() {
    return Material(
        vec3(0),
        0,
        vec3(0),
        0
    );
}

HomogenousVolume createEmptyHomogenousVolume() {
    return HomogenousVolume(vec3(0), 0, vec3(0), 0, vec3(0), 0, vec3(0), 0, vec3(0), 0);
}

Hit createEmptyHit() {
    return Hit(
        HIT_MISS,
        -1, -1, -1, // t, tNear, and tFar
        vec3(0),
        vec3(0),
        NULL_TYPE,
        createEmptyMaterial(),
        createEmptyHomogenousVolume()
    );
}

Hit intersectSphere(Ray ray, Sphere sphere) {
    vec3 oc = ray.origin - sphere.position;
    float a = dot(ray.dir, ray.dir); // should be 1 if normalized
    float b = 2 * dot(oc, ray.dir);
    float c = dot(oc, oc) - sphere.radius * sphere.radius;

    float discriminant = b * b - 4 * a * c;

    Hit noHit = createEmptyHit();
    noHit.didHit = HIT_MISS;

    if (discriminant < 0) return noHit;

    float sqrtDisc = float(sqrt(discriminant));
    float t1 = (-b - sqrtDisc) / (2 * a);
    float t2 = (-b + sqrtDisc) / (2 * a);

    float t;

    if (t1 > 1e-4) t = t1;
    else if (t2 > 1e-4) t = t2;
    else return noHit;

    vec3 hitPoint = ray.origin + t * ray.dir;
    vec3 normal = normalize(hitPoint - sphere.position);

    return Hit(HIT_SUCCESS, t, 0, 0, hitPoint, normal, SPHERE, sphere.mat, createEmptyHomogenousVolume());
}

Hit intersectTriangle(Ray ray, Triangle triangle) {
    vec3 v0 = triangle.v0;
    vec3 v1 = triangle.v1;
    vec3 v2 = triangle.v2;

    vec3 edge1 = v1 - v0;
    vec3 edge2 = v2 - v0;

    vec3 h = cross(ray.dir, edge2);
    float a = dot(edge1, h);

    Hit noHit = createEmptyHit();
    noHit.didHit = HIT_MISS;

    if (-1e-4 < a && a < 1e-4) return noHit;

    float f = 1.0f / a;
    vec3 s = ray.origin - v0;
    float u = f * dot(s, h);

    if (u < 0 || u > 1) {
        return noHit; // outside triangle
    }

    vec3 q = cross(s, edge1);
    float v = f * dot(ray.dir, q);

    if (v < 0 || (u + v) > 1) {
        return noHit;
    }

    float t = f * dot(edge2, q);

    if (t > 1e-4) { // intersection in front of ray
        vec3 hitPoint = ray.origin + (t - 1e-4) * ray.dir;
        vec3 normal = normalize(cross(edge1, edge2));
        if (dot(normal, ray.dir) > 0) {
            normal *= -1; // flip normal if facing wrong direction
        }
        return Hit(HIT_SUCCESS, t, 0, 0, hitPoint, normal, TRIANGLE, triangle.mat, createEmptyHomogenousVolume());
    }
    else {
        return noHit;
    }
}

Hit intersectHomogenousVolume(Ray ray, HomogenousVolume volume) {
    // simple aabb intersection
    vec3 invDir = 1.0 / ray.dir;
    vec3 t1 = (volume.minXYZ - ray.origin) * invDir;
    vec3 t2 = (volume.maxXYZ - ray.origin) * invDir;

    // find near and far t values
    float tNear = max(max(min(t1.x, t2.x), min(t1.y, t2.y)), min(t1.z, t2.z));

    float tFar = min(min(max(t1.x, t2.x), max(t1.y, t2.y)), max(t1.z, t2.z));

    // check for intersection
    if (tNear <= tFar && tFar >= 0) {
        // Return distance 'tNear' (if ray is outside) or 'tFar' (if inside)
        float t = tNear < 0 ? tFar : tNear;
        vec3 hitPoint = ray.origin + t * ray.dir;
        
        // IMPORTANT: setting normal to vec3(0) indicates to the trace function that the ray has hit a volume

        return Hit(HIT_SUCCESS, t, tNear - 1e-3, tFar + 1e-3, hitPoint, vec3(0), VOLUME, createEmptyMaterial(), volume);
    }

    Hit noHit = createEmptyHit();
    noHit.didHit = HIT_MISS;

    return noHit; // No intersection
}

Hit findClosestVolume(Ray ray) {
    Hit closestVolumeHit = createEmptyHit();
    int firstVolume = 1;

    // finally, lets do participating media
    for (int i = 0; i < homogenousVolumesCount; i++) {
        Hit hit = intersectHomogenousVolume(ray, homogenousVolumes[i]);
        if (hit.didHit == HIT_MISS) continue;
        if (firstVolume == 1) {
            firstVolume = 0;
            closestVolumeHit = hit;
        }
        else if (hit.t < closestVolumeHit.t) {
            closestVolumeHit = hit;
        }
    }

    return closestVolumeHit;
}

Hit findClosestSurface(Ray ray) {
    Hit closestHit = createEmptyHit();
    int first = 1;
    
    // for now, all objects are spheres. in the future will add a triangle
    for (int i = 0; i < sphereCount; i++) {
        Hit hit = intersectSphere(ray, spheres[i]);
        if (hit.didHit == HIT_MISS) continue;
        if (first == 1) {
            first = 0;
            closestHit = hit;
        }
        else if (hit.t < closestHit.t) {
            closestHit = hit;
        }
    }

    // repeat for triangle using intersectTriangle
    for (int i = 0; i < triangleCount; i++) {
        Hit hit = intersectTriangle(ray, triangles[i]);
        if (hit.didHit == HIT_MISS) continue;
        if (first == 1) {
            first = 0;
            closestHit = hit;
        }
        else if (hit.t < closestHit.t) {
            closestHit = hit;
        }
    }

    // for now, all objects are spheres. in the future will add a triangle
    for (int i = 0; i < emissiveSpheresCount; i++) {
        Hit hit = intersectSphere(ray, emissiveSpheres[i]);
        if (hit.didHit == HIT_MISS) continue;
        if (first == 1) {
            first = 0;
            closestHit = hit;
        }
        else if (hit.t < closestHit.t) {
            closestHit = hit;
        }
    }

    // repeat for triangle using intersectTriangle
    for (int i = 0; i < emissiveTrianglesCount; i++) {
        Hit hit = intersectTriangle(ray, emissiveTriangles[i]);
        if (hit.didHit == HIT_MISS) continue;
        if (first == 1) {
            first = 0;
            closestHit = hit;
        }
        else if (hit.t < closestHit.t) {
            closestHit = hit;
        }
    }

    return closestHit;
}

bool isInShadow(Ray shadowRay, float maxDist) {
    Hit closestHit = createEmptyHit();
    int first = 1;
    
    // for now, all objects are spheres. in the future will add a triangle
    for (int i = 0; i < sphereCount; i++) {
        Hit hit = intersectSphere(shadowRay, spheres[i]);
        if (hit.didHit == HIT_SUCCESS && hit.t <= maxDist) return true;
    }

    // repeat for triangle using intersectTriangle
    for (int i = 0; i < triangleCount; i++) {
        Hit hit = intersectTriangle(shadowRay, triangles[i]);
        if (hit.didHit == HIT_SUCCESS && hit.t <= maxDist) return true;
    }

    return false;
}

vec3 randomUnitVec3() {
    float theta = randf() * 6.28318530718; // 2 * pi
    float u = randf() * 2.0 - 1.0;
    float a = sqrt(1.0 - u * u);
    return vec3(a * cos(theta), a * sin(theta), u);
}

vec3 randomCosineWeightedDir(vec3 normal) {
    // Cosine-weighted hemisphere sample (local space)
    float r1 = randf();
    float r2 = randf();

    float phi = 6.28318530718 * r1; // 2 * PI
    float x = cos(phi) * sqrt(r2);
    float y = sin(phi) * sqrt(r2);
    float z = sqrt(1.0 - r2);

    // Build an orthonormal basis from the normal
    vec3 tangent;
    if (abs(normal.z) < 0.999)
        tangent = normalize(cross(vec3(0.0, 0.0, 1.0), normal));
    else
        tangent = normalize(cross(vec3(0.0, 1.0, 0.0), normal));

    vec3 bitangent = cross(normal, tangent);

    // Transform from tangent space to world space
    vec3 diffuseDir = normalize(
        tangent * x +
        bitangent * y +
        normal * z
    );

    return diffuseDir;
}

vec3 getNonParallelVector(vec3 v) {
    if (dot(v, v) < 1e-4) {
        return vec3(1.0, 0.0, 0.0);
    }

    vec3 absV = abs(v);
    
    vec3 basis;
    if (absV.x <= absV.y && absV.x <= absV.z) {
        basis = vec3(1.0, 0.0, 0.0);
    } else if (absV.y <= absV.x && absV.y <= absV.z) {
        basis = vec3(0.0, 1.0, 0.0);
    } else {
        basis = vec3(0.0, 0.0, 1.0);
    }

    // the cross product is guaranteed to be perpendicular (and not parallel) to v
    return cross(v, basis);
}

vec3 randomPointOnHemisphereToPoint(Sphere sphere, vec3 source) {
    float u = randf();
    float v = randf();

    float phi = 2.0 * PI * u;
    float z = 2.0 * v - 1.0;
    float r = sqrt(1.0 - z * z);

    vec3 normal = vec3(
        r * cos(phi),
        r * sin(phi),
        z
    );

    vec3 targetDir = normalize(source - sphere.position);

    if (dot(normal, targetDir) < 0) {
        normal *= -1;
    }

    vec3 lightPoint = sphere.position + sphere.radius * normal;
    return lightPoint;
}

vec3 randomPointOnTriangle(Triangle triangle) {
    float r1 = randf();
    float r2 = randf();
    float sqrt_r1 = sqrt(r1);

    float u = 1 - sqrt_r1;
    float v = r2 * sqrt_r1;
    float w = 1 - u - v;

    vec3 lightPoint = u * triangle.v0 + v * triangle.v1 + w * triangle.v2;
    return lightPoint;
}

// FOR TESTING PURPOSES ONLY

// Helper function to generate a random 0-1 float from a vec3
float hash(vec3 p) {
    p = fract(p * 0.1031);
    p += dot(p, p.zyx + 31.32);
    return fract((p.x + p.y) * p.z);
}

// 3D Noise function taking in vec3 and outputting 0 to 1 float
float noise3(vec3 x) {
    vec3 i = floor(x);
    vec3 f = fract(x);
    
    // Smoothstep for cubic interpolation
    vec3 u = f * f * (3.0 - 2.0 * f);

    // 8 corners of the 3D grid cube
    float a = hash(i + vec3(0.0, 0.0, 0.0));
    float b = hash(i + vec3(1.0, 0.0, 0.0));
    float c = hash(i + vec3(0.0, 1.0, 0.0));
    float d = hash(i + vec3(1.0, 1.0, 0.0));
    float e = hash(i + vec3(0.0, 0.0, 1.0));
    float f_ = hash(i + vec3(1.0, 0.0, 1.0));
    float g = hash(i + vec3(0.0, 1.0, 1.0));
    float h = hash(i + vec3(1.0, 1.0, 1.0));

    // Trilinear interpolation of the 8 corners
    return mix(mix(mix(a, b, u.x), mix(c, d, u.x), u.y),
               mix(mix(e, f_, u.x), mix(g, h, u.x), u.y), u.z);
}

float fbm(vec3 p) {
    float value = 0.0;
    float amplitude = 0.5;

    for (int i = 0; i < 3; i++) {
        value += amplitude * noise3(p);

        p *= 2.02;
        amplitude *= 0.5;
    }

    return value;
}

float cloudDensity(vec3 p, HomogenousVolume volume) {
    vec3 normalized = p - volume.minXYZ;
    normalized /= volume.maxXYZ - volume.minXYZ;
    return texture(densityTexture, normalized).r;
    // Large-scale cloud structure
    float macro = fbm(p * 0.05);

    if (macro < 0.000001) return 0; // just testing

    // Domain warp
    float w = fbm(p * 0.25 + vec3(31,17,11));
    // vec3 warp = vec3(
    //     fbm(p * 0.25 + vec3(31,17,11)),
    //     fbm(p * 0.25 + vec3(12,51,3)),
    //     fbm(p * 0.25 + vec3(7,9,41))
    // );
    vec3 warp = vec3(w);

    warp = warp * 2.0 - 1.0;

    // Fine detail
    float detail = fbm((p + warp * 3.0) * 1.5);

    float density = macro - 0.8 * detail;

    density = smoothstep(0.2, 0.4, density);
    // float coverage = 0.55; // higher = thicker clouds
    // density = smoothstep(coverage, 1.0, density);
    // density = pow(density, 0.6);

    return density;
}

// for now just assume one single volume
vec3 getTransmittance(Ray ray, HomogenousVolume volume, float maxDistance) {
    vec3 transmittance = vec3(1.0);

    Hit hit = intersectHomogenousVolume(ray, volume);

    float entryT = max(hit.tNear, 0);
    float exitT = min(hit.tFar, maxDistance);

    float travelledT = entryT;

    vec3 majorantExtinctionCoefficient = volume.extinctionCoefficient;
    float maxMajorantExtinctionComponent = max(max(majorantExtinctionCoefficient.x, majorantExtinctionCoefficient.y), majorantExtinctionCoefficient.z);

    while (travelledT < exitT) { 
        float sampledDistance = -log(randf()) / maxMajorantExtinctionComponent;
        travelledT += sampledDistance;

        if (travelledT >= exitT) {
            break;
        }

        float density = cloudDensity(ray.origin + travelledT * ray.dir, volume);
        vec3 localExtinctionCoefficient = density * majorantExtinctionCoefficient;

        vec3 acceptProbability = localExtinctionCoefficient / majorantExtinctionCoefficient;

        transmittance *= (vec3(1.0) - acceptProbability);
    }

    return transmittance;
}

struct TraceData {
    Ray ray;
    vec3 incomingLight;
    vec3 rayColor;
};

TraceData shadeSurface(Ray ray, vec3 incomingLight, vec3 rayColor, Hit hitSurface) {
    if (hitSurface.didHit == HIT_SUCCESS) { // just in case
        // use NEE for surface here

        vec3 point = hitSurface.position;
        vec3 normal = hitSurface.normal;
        Material mat = hitSurface.mat;

        // directly sampling light sources to estimate (brings down noise super fast)
        for (int i = 0; i < emissiveSpheresCount; i++) {
            Sphere sphere = emissiveSpheres[i];
            vec3 lightPoint = randomPointOnHemisphereToPoint(sphere, point);
            vec3 shadowDir = normalize(lightPoint - hitSurface.position);
            Ray shadowRay = Ray(hitSurface.position + 1e-4 * normal, shadowDir);
            if (isInShadow(shadowRay, length(lightPoint - hitSurface.position))) continue; // this light does not contribute anything

            // light normal on sphere
            vec3 lightNormal = normalize(lightPoint - sphere.position);

            // i cant lie this is all chatgpt. idk wtf MIS is
            float dist2 = dot(lightPoint - point, lightPoint - point);
            vec3 wi = normalize(lightPoint - point);

            float cos_surface = max(dot(normal, wi), 0.0);
            float cos_light = max(dot(lightNormal, -wi), 0.0);

            float area = 2.0 * PI * sphere.radius * sphere.radius; // 4pir^2 / 2 = 2pir^2 cuz only sampling hemisphere

            float p_light = dist2 / (area * cos_light + 1e-4);
            float p_bsdf = cos_surface / PI;

            float w = (p_light * p_light) /
                    (p_light * p_light + p_bsdf * p_bsdf);

            vec3 Le = sphere.mat.emissionColor * sphere.mat.emissionStrength;
            vec3 f = mat.color / PI;

            // finally, get the transmittance along shadow ray if it exists and multiply to the contribution

            vec3 transmittance = vec3(1);
            Hit findVolume = findClosestVolume(shadowRay);
            if (findVolume.didHit == HIT_SUCCESS) {
                transmittance = getTransmittance(shadowRay, findVolume.volume, length(lightPoint - point));
            }

            incomingLight += rayColor * transmittance * Le * f * cos_surface / (p_light + 1e-4) * w;
        }

        ray.origin = hitSurface.position + 1e-4f * normal;
        vec3 diffuseDir = randomCosineWeightedDir(normal); // random hemisphere cosine weighted direction
        vec3 specularDir = reflect(ray.dir, normal);
        ray.dir = mix(diffuseDir, specularDir, mat.reflectivity);

        vec3 emittedLight = mat.emissionStrength * mat.emissionColor; // this object will emit light back into the camera
        incomingLight += emittedLight * rayColor; // tint the color via the ray color so far
        rayColor *= mat.color; // ray color absorbs some of the material's color
    }
    return TraceData(ray, incomingLight, rayColor);
}

Ray scatter(Ray ray, vec3 scatterPoint) {
    // Henyey-Greenstein phase function gives cos(theta), where theta is the polar angle
    // of the new direction relative to the original ray origin + direction
    // Read here for more detail: https://zydak.github.io/Clouds/index.html
    float e3 = randf();
    float cos_theta;
    if (abs(g) < 1e-4) {
        cos_theta = 2 * e3 - 1;
    }
    else {
        cos_theta = 1 / (2 * g) * (1 + g * g - pow((1 - g * g) / (1 - g + 2 * g * e3), 2));
    }

    // float sin_theta = sin(acos(cos_theta));
    cos_theta = clamp(cos_theta, -1.0, 1.0); // clamp is just in case of floating error
    float sin_theta = sqrt(max(0.0, 1.0 - cos_theta * cos_theta)); // this is faster

    float e4 = randf();
    float phi = 6.28318530718 * e4; // 2piE, where E = Uniform(0, 1)

    vec3 u = getNonParallelVector(ray.dir);
    vec3 v = normalize(ray.dir);
    
    vec3 t = normalize(cross(u, v));
    vec3 b = cross(v, t);
    vec3 w = sin_theta * cos(phi) * t + sin_theta * sin(phi) * b + cos_theta * v;
    w = normalize(w); // just in case lmao

    ray.origin = scatterPoint + 1e-4 * w;
    ray.dir = w; // this is new direction

    return ray;
}

float HenyeyGreensteinPhaseFunction(vec3 incomingLightDir, vec3 outgoingLightDir) {
    float nominator = 1 - g * g;
    float cos_theta = dot(incomingLightDir, outgoingLightDir);
    float denominator = 4 * PI * pow(1 + g * g - 2 * g * cos_theta, 1.5);
    return nominator / denominator;
}

vec3 traceRay(Ray ray) {
    vec3 incomingLight = vec3(0);
    vec3 rayColor = vec3(1);

    TraceData data = TraceData(ray, incomingLight, rayColor);

    for (int depth = 0; depth < MAX_DEPTH; depth++) {
        Hit hitSurface = findClosestSurface(ray); // surface hit
        Hit hitVolume = findClosestVolume(ray);

        if (hitSurface.didHit == HIT_MISS && hitVolume.didHit == HIT_MISS) {
            vec3 skyColor = vec3(0.5, 0.7, 1.0);
            incomingLight += skyColor * rayColor;
            break; // ray did not hit anything (hit the sky) can safely exit
        }

        // Surface first
        // either no volume was hit or it was hit but a surface was also hit and the surface was hit before the volume was
        if (hitVolume.didHit == HIT_MISS || (hitSurface.didHit == HIT_SUCCESS && hitSurface.t < hitVolume.t)) {
            // shade surface (if it exists)
            TraceData data = shadeSurface(ray, incomingLight, rayColor, hitSurface);
            ray = data.ray;
            incomingLight = data.incomingLight;
            rayColor = data.rayColor;
            continue;
        }
        
        // Volume first
        float entryT = max(hitVolume.tNear, 0.0);
        float exitT = hitVolume.tFar;

        bool surfaceInsideVolume = hitSurface.didHit == HIT_SUCCESS && hitSurface.t >= entryT && hitSurface.t <= exitT;

        if (surfaceInsideVolume) {
            exitT = hitSurface.t;
        }

        HomogenousVolume volume = hitVolume.volume;

        vec3 majorantExtinctionCoefficient = volume.extinctionCoefficient;
        float maxMajorantExtinctionComponent = max(max(majorantExtinctionCoefficient.x, majorantExtinctionCoefficient.y), majorantExtinctionCoefficient.z);

        // delta tracking
        float travelledT = entryT;

        bool absorbRay = false;

        while (travelledT < exitT) {
            float sampledDistance = -log(randf()) / maxMajorantExtinctionComponent; // standard closed form free path length for homogeneous volumes, using majorant coefficient

            travelledT += sampledDistance;

            // Surface before scattering
            if (travelledT >= exitT) {
                if (surfaceInsideVolume) {
                    TraceData data = shadeSurface(ray, incomingLight, rayColor, hitSurface);
                    ray = data.ray;
                    incomingLight = data.incomingLight;
                    rayColor = data.rayColor;
                    break;
                }
                else { // ray left medium
                    ray.origin += (hitVolume.tFar + 1e-4) * ray.dir;
                    // no beer's law now, at least thats just according to chatgpt
                    break;
                }
            }
            else {
                float density = cloudDensity(ray.origin + travelledT * ray.dir, volume);

                vec3 localScatteringCoefficient = density * volume.scatteringCoefficient;
                vec3 localAbsorptionCoefficient = density * volume.absorptionCoefficient;
                vec3 localExtinctionCoefficient = localScatteringCoefficient + localAbsorptionCoefficient;

                float maxLocalExtinctionComponent = max(max(localExtinctionCoefficient.x, localExtinctionCoefficient.y), localExtinctionCoefficient.z);

                float acceptanceProbability = maxLocalExtinctionComponent / maxMajorantExtinctionComponent;

                if (randf() > acceptanceProbability) {
                    continue; // null collision, keep sampling
                }

                // simulate real interaction
                float maxLocalScatteringCoefficient = max(max(localScatteringCoefficient.x, localScatteringCoefficient.y), localScatteringCoefficient.z);

                float scatterProbability = maxLocalScatteringCoefficient / maxLocalExtinctionComponent;

                if (randf() < scatterProbability) {
                    // scatter
                    vec3 scatterPoint = ray.origin + travelledT * ray.dir; // this should be renamed in the struct to hitPoint but whatever

                    vec3 localAlbedo = localScatteringCoefficient / (localExtinctionCoefficient + vec3(1e-4));
                    rayColor *= localAlbedo / (scatterProbability + 1e-4);

                    // direct light sampling for homogeneous volumes
                    for (int i = 0; i < emissiveSpheresCount; i++) {
                        Sphere sphere = emissiveSpheres[i];
                        vec3 lightPoint = randomPointOnHemisphereToPoint(sphere, scatterPoint);
                        vec3 lightNormal = normalize(lightPoint - sphere.position);
                        vec3 wo = -ray.dir; // out going light direction
                        vec3 wi = normalize(lightPoint - scatterPoint); // direction from scatter point to light source
                        float dist = length(lightPoint - scatterPoint); // distance from scatter point to light source

                        // check for visibility
                        Ray shadowRay = Ray(scatterPoint, wi);

                        if (isInShadow(shadowRay, dist)) { // opaque object blocks light, this light source is not a direct light source
                            continue;
                        }

                        // NOTE: this does NOT stack volumes. treats everything outside of current volume as vacuum, ie doesnt track any other homogenous volumes in the scene
                        HomogenousVolume volume = hitVolume.volume;

                        vec3 transmittance = getTransmittance(shadowRay, volume, dist);
                        
                        float phase = HenyeyGreensteinPhaseFunction(wi, wo);
                        float area = 2 * PI * sphere.radius * sphere.radius; // hemisphere area
                        float cosLight = max(dot(lightNormal, -wi), 0.0);

                        float pdf = dist*dist / (area * cosLight);
                        vec3 emittedLight = sphere.mat.emissionStrength * sphere.mat.emissionColor;

                        // this is the final direct light contribution
                        vec3 directLightSamplingContribution = transmittance * emittedLight * localScatteringCoefficient * phase / pdf;
                        incomingLight += rayColor * directLightSamplingContribution;
                    }

                    // no beer's law

                    ray = scatter(ray, scatterPoint);
                }
                else {
                    // absorb
                    absorbRay = true;
                }

                break; // no more sampling after found real interaction
            }
        }

        if (absorbRay) break;

        if (depth >= 3) { // dont do russian roulette for the first few bounces
            float p = max(max(rayColor.r, rayColor.g), rayColor.b);
            p = clamp(p, 0.05, 0.95);

            if (randf() > p) {
                break; // early termination
            }

            rayColor /= p; // balance out early ray terminations
        }
    }

    // this is a quick hack for disabling fireflies, at the expense of making things less bright in general

    // if (incomingLight.x > 1 || incomingLight.y > 1 || incomingLight.z > 1) {
    //     float largest = max(max(incomingLight.x, incomingLight.y), incomingLight.z);
    //     incomingLight /= largest;
    // }

    return incomingLight;
}

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    if (coord.x >= width || coord.y >= height) return;
    vec3 color = imageLoad(pixels, coord).xyz;
    state = uint(uint(coord.x) * 1973u + uint(coord.y) * 9277u + uint(totalFrameCount) * 26699u) | uint(1);

    for (int i = 0; i < NUM_SAMPLES; i++) {
        Ray ray = makeRayFromCameraThroughPixel();
        color += traceRay(ray);
    }
    imageStore(pixels, coord, vec4(color, 1)); // compute shader just accumulates
}